### ISSUE TITLE
this is not really a issue but a suggestion: wozzol.nl

### ISSUE THREAD

**Issue by gamepier** [dawnsgrave/Duolingo-Account-Generator-Email-Spammer#1]
So there is something like duolingo where you can spam thousands of emails using it but i just like don't know how to code and this site is called wozzol.nl where you can sign up and really easily with the plus method crate another account over and over again

**Comment by dawnsgrave** [comment]
ill look into it

**Comment by dawnsgrave** [comment]
it's done, message me on telegram: @dawnsgrave
